name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttihp25b

      - name: Upload Docs artifact
        uses: actions/upload-artifact@v4   # ✅ updated to v4
        with:
          name: github-pages-docs
          path: ./docs/_site
